- name: Create AppImage using linuxdeploy (Linux)
  if: runner.os == 'Linux'
  run: |
    # Install linuxdeploy and PyInstaller plugin
    sudo wget -O /usr/local/bin/linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
    sudo chmod a+x /usr/local/bin/linuxdeploy
    sudo wget -O /usr/local/bin/linuxdeploy-plugin-pyinstaller https://github.com/linuxdeploy/linuxdeploy-plugin-pyinstaller/releases/download/continuous/linuxdeploy-plugin-pyinstaller-x86_64.AppImage
    sudo chmod a+x /usr/local/bin/linuxdeploy-plugin-pyinstaller

    # Create AppDir
    mkdir -p ./AppDir/usr/bin
    cp ./dist/BSM ./AppDir/usr/bin/

    # Create desktop file
    echo "[Desktop Entry]
    Name=BSM
    Exec=/usr/bin/BSM
    Type=Application" > ./AppDir/BSM.desktop

    # Create AppImage
    linuxdeploy --appdir ./AppDir --plugin pyinstaller --output appimage --verbose
  shell: bash