name: Build Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt6 pyinstaller
          if [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libxcb-shape0 libxkbcommon-x11-0 libxcb-cursor0
          fi
        shell: bash

      - name: Build application using PyInstaller
        run: |
          pyinstaller --clean --onefile --distpath ./dist --workpath ./build BSM.py
        shell: bash

      - name: Create AppImage using linuxdeploy (Linux)
        if: runner.os == 'Linux'
        run: |
          # Install linuxdeploy and PyInstaller plugin
          sudo wget https://github.com/linuxdeploy/linuxdeploy/releases/download/2.2.1/linuxdeploy-x86_64.AppImage -O /usr/local/bin/linuxdeploy
          sudo chmod a+x /usr/local/bin/linuxdeploy
          sudo wget https://github.com/linuxdeploy/linuxdeploy-plugin-pyinstaller/releases/download/0.1/linuxdeploy-plugin-pyinstaller-x86_64.AppImage -O /usr/local/bin/linuxdeploy-plugin-pyinstaller
          sudo chmod a+x /usr/local/bin/linuxdeploy-plugin-pyinstaller

          # Create AppDir
          mkdir -p ./AppDir/usr/bin
          cp ./dist/BSM ./AppDir/usr/bin/

          # Create desktop file
          echo "[Desktop Entry]
          Name=BSM
          Exec=BSM
          Type=Application" > ./AppDir/BSM.desktop

          # Create AppImage
          linuxdeploy --appdir ./AppDir --plugin pyinstaller --output appimage
        shell: bash

      - name: Upload .exe artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: BSM.exe
          path: ./dist/BSM.exe

      - name: Upload .AppImage artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: BSM.AppImage
          path: ./BSM-*.AppImage