name: Build Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create AppImage (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          cp ./dist/BSM AppDir/usr/bin/
          chmod +x AppDir/usr/bin/BSM
          echo "[Desktop Entry]" > AppDir/usr/share/applications/BSM.desktop
          echo "Name=BSM" >> AppDir/usr/share/applications/BSM.desktop
          echo "Comment=My awesome BSM application" >> AppDir/usr/share/applications/BSM.desktop
          echo "Exec=BSM" >> AppDir/usr/share/applications/BSM.desktop
          echo "Icon=BSM" >> AppDir/usr/share/applications/BSM.desktop
          echo "Terminal=false" >> AppDir/usr/share/applications/BSM.desktop
          echo "Type=Application" >> AppDir/usr/share/applications/BSM.desktop
          echo "Categories=Utility;" >> AppDir/usr/share/applications/BSM.desktop
          touch AppDir/usr/share/icons/hicolor/256x256/apps/BSM.png
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool.AppImage
          chmod +x appimagetool.AppImage
          ./appimagetool.AppImage AppDir
  
      - name: Install dependencies for Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install -U pip
          pip install pyinstaller PyQt6

      - name: Build application using PyInstaller
        run: |
          pyinstaller --onefile --distpath ./dist --workpath ./build BSM.py
        working-directory: ${{ github.workspace }}

      - name: Create AppImage (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p AppDir/usr/bin
          cp ./dist/BSM AppDir/usr/bin/
          chmod +x AppDir/usr/bin/BSM
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool.AppImage
          chmod +x appimagetool.AppImage
          ./appimagetool.AppImage AppDir

      - name: Upload .exe artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: BSM.exe
          path: ./dist/BSM.exe

      - name: Upload .AppImage artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: BSM.AppImage
          path: ./dist/BSM.AppImage