name: Build Python App

on:
  push:
    branches:
      - main  # Срабатывает при коммите в ветку main
  pull_request:
    branches:
      - main  # Срабатывает при создании Pull Request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Запуск на Linux для AppImage
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Разделяем сборку для Linux и Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Укажите версию Python

      - name: Install dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y \
            build-essential \
            libfuse2 \
            pyqt6 \
            pyinstaller \
            libssl-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            curl \
            libncurses5-dev \
            libgdbm-dev \
            liblzma-dev \
            tk-dev \
            libffi-dev \
            zlib1g-dev \
            libglib2.0-dev \
            libfontconfig1 libx11-6 libxext6 \
            wget
          pip install pyinstaller

      - name: Install dependencies for Windows
        if: runner.os == 'Windows'
        run: |
          choco install python --version=3.10
          pip install pyinstaller

      - name: Build application using PyInstaller
        run: |
          pyinstaller --onefile --distpath ./dist --workpath ./build app.py
        working-directory: ${{ github.workspace }}

      - name: Create AppImage (Linux)
        if: runner.os == 'Linux'
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool.AppImage
          chmod +x appimagetool.AppImage
          ./appimagetool.AppImage ./dist/appname

      - name: Upload .exe artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: appname.exe
          path: ./dist/appname.exe

      - name: Upload .AppImage artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: appname.AppImage
          path: ./dist/appname.AppImage

