name: Build Python App

on:
  push:
    branches:
      - main  # Срабатывает при коммите в ветку main
  pull_request:
    branches:
      - main  # Срабатывает при создании Pull Request в ветку main

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Используем matrix.os вместо фиксированного значения
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Разделяем сборку для Linux и Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libfuse2 \
            libssl-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            curl \
            libncurses5-dev \
            libgdbm-dev \
            liblzma-dev \
            tk-dev \
            libffi-dev \
            zlib1g-dev \
            libglib2.0-dev \
            libfontconfig1 libx11-6 libxext6 \
            wget
          pip install -U pip
          pip install pyinstaller PyQt6

      - name: Install dependencies for Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install -U pip
          pip install pyinstaller PyQt6

      - name: Build application using PyInstaller
        run: |
          pyinstaller --onefile --distpath ./dist --workpath ./build ./BSM.py
        working-directory: ${{ github.workspace }}

      - name: Upload .exe artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: BSM.exe
          path: ./dist/BSM.exe

      - name: Create AppImage (Linux)
        if: runner.os == 'Linux'
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool.AppImage
          chmod +x appimagetool.AppImage
          ./appimagetool.AppImage ./dist/BSM

      - name: Upload .AppImage artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: BSM.AppImage
          path: ./dist/BSM.AppImage
